org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

# Minecraft / NeoForge
minecraft_version=26.3
minecraft_version_range=[26.3,26.4)
neo_version=26.3.0.41-beta
neo_version_range=[26.3,)
loader_version_range=[4,)

# Mod
mod_id=ancient_trees
mod_name=Ancient Trees Reworked
mod_license=MIT
mod_version=0.1.0
mod_group_id=com.lays24mc.ancient_trees
mod_authors=Lays24MC (Rewrite); ScottKillen, Blorph, Ruyuna (Original Dendrology)
mod_description=Thirteen new tree species for Minecraft. A rewrite of Ancient Trees / Dendrology.
